apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: app-secret
  data:
    - secretKey: username
      remoteRef:
        key: eks-rds-secret
        property: username

    - secretKey: password
      remoteRef:
        key: eks-rds-secret
        property: password

    - secretKey: host
      remoteRef:
        key: eks-rds-secret
        property: host

    - secretKey: dbname
      remoteRef:
        key: eks-rds-secret
        property: dbname